sudo: required
services:
- docker
before_install: true
install:
- docker build -t kernsuite/cattery .
before_script: true
script:
- docker run kernsuite/cattery
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: LW8gBbuZXiMH+IBMD4kVoEt1qUXCOZTsn9QKgX4s4Ta79dBSSaAjZXTAlVZs3JCAjrQ53erLrffsJezwLCrSFRTHHlyHSdiDmomdvHTfwzfZsShv8ZhbN3V8LAGG812ZIVMzOf8IWwodWxlJWK9GvWcPSWCHXUnXUUQ+/kCCHyE=
  on:
    tags: true
    repo: ska-sa/meqtrees-cattery
